name: Delete UAT preview deployment after PR is merged or closed

on:
  workflow_dispatch:
  pull_request:
    types: [ closed ]

permissions:
  contents: read

jobs:
  cleanup-uat:
    runs-on: ubuntu-24.04
    environment: uat
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Cleanup UAT preview
        uses: ./.github/actions/cleanup_branch
        with:
          kube-cert: ${{ secrets.KUBE_CERT }}
          kube-token: ${{ secrets.KUBE_TOKEN }}
          kube-cluster: ${{ secrets.KUBE_CLUSTER }}
          kube-namespace: ${{ secrets.KUBE_NAMESPACE }}
          pr-number: ${{ github.event.pull_request.number }}

